
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package compiladorhg;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int id = 8;
  public static final int espacio = 9;
  public static final int menr = 6;
  public static final int mail = 5;
  public static final int EOF = 0;
  public static final int num = 2;
  public static final int mayr = 7;
  public static final int error = 1;
  public static final int dire = 4;
  public static final int deci = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "num",
  "deci",
  "dire",
  "mail",
  "menr",
  "mayr",
  "id",
  "espacio"
  };
}

